### ISSUE TITLE
[BUG] AttributeError on calling fit()

### ISSUE THREAD

**Issue by zariiii9003** [dynamicslab/pysindy#138]
I'm trying the library (v1.3.0, python 3.8) for the first time and i'm getting an error message that is not very helpful.
`data` is a numpy array with shape `(130439, 4)`

### Reproducing code example:

```python3
import numpy as np
import pysindy as ps

# %% read data
data = np.load("data.npy").astype(np.float64)

# %% fit
dt = 0.001
sr3_optimizer = ps.SR3()
model = ps.SINDy(optimizer=sr3_optimizer).fit(x=data[:, 2:], u=data[:, :2], t=dt, quiet=True)
model.print()
```

### Error message:

```
Traceback (most recent call last):

  File "C:\working_directory\sys_ident.py", line 16, in <module>
    model = ps.SINDy(optimizer=sr3_optimizer).fit(x=data[:, 2:], u=data[:, :2], t=dt, quiet=True)

  File "C:\Users\Miniconda3\envs\py38\lib\site-packages\pysindy\pysindy.py", line 292, in fit
    self.model.fit(x, x_dot)

  File "C:\Users\Miniconda3\envs\py38\lib\site-packages\sklearn\pipeline.py", line 390, in fit
    Xt = self._fit(X, y, **fit_params_steps)

  File "C:\Users\Miniconda3\envs\py38\lib\site-packages\sklearn\pipeline.py", line 348, in _fit
    X, fitted_transformer = fit_transform_one_cached(

  File "C:\Users\Miniconda3\envs\py38\lib\site-packages\joblib\memory.py", line 349, in __call__
    return self.func(*args, **kwargs)

  File "C:\Users\Miniconda3\envs\py38\lib\site-packages\sklearn\pipeline.py", line 893, in _fit_transform_one
    res = transformer.fit_transform(X, y, **fit_params)

  File "C:\Users\Miniconda3\envs\py38\lib\site-packages\sklearn\base.py", line 850, in fit_transform
    return self.fit(X, y, **fit_params).transform(X)

  File "C:\Users\Miniconda3\envs\py38\lib\site-packages\pysindy\feature_library\polynomial_library.py", line 170, in fit
    self.n_input_features_ = n_features

AttributeError: can't set attribute
```

### PySINDy/Python version information:

<details>
<summary>My conda environment</summary>

```
# Name                    Version                   Build  Channel
alabaster                 0.7.12                     py_0    conda-forge
argh                      0.26.2          pyh9f0ad1d_1002    conda-forge
arrow                     1.2.1              pyhd8ed1ab_0    conda-forge
asammdf                   6.4.4              pyhe74cb21_0    conda-forge
astroid                   2.9.0            py38haa244fe_0    conda-forge
async_generator           1.10                       py_0    conda-forge
atomicwrites              1.4.0              pyh9f0ad1d_0    conda-forge
attrs                     21.2.0             pyhd8ed1ab_0    conda-forge
autopep8                  1.6.0              pyhd8ed1ab_1    conda-forge
babel                     2.9.1              pyh44b312d_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
bcrypt                    3.2.0            py38h294d835_2    conda-forge
binaryornot               0.4.4                      py_1    conda-forge
black                     21.11b1            pyhd8ed1ab_0    conda-forge
bleach                    4.1.0              pyhd8ed1ab_0    conda-forge
brotli                    1.0.9                h8ffe710_6    conda-forge
brotli-bin                1.0.9                h8ffe710_6    conda-forge
brotlipy                  0.7.0           py38h294d835_1003    conda-forge
ca-certificates           2021.10.8            h5b45459_0    conda-forge
canmatrix                 0.8                        py_0    conda-forge
cchardet                  2.1.5            py38hb99c5c2_1    conda-forge
certifi                   2021.10.8        py38haa244fe_1    conda-forge
cffi                      1.15.0           py38hd8c33c5_0    conda-forge
chardet                   4.0.0            py38haa244fe_2    conda-forge
charset-normalizer        2.0.9              pyhd8ed1ab_0    conda-forge
click                     8.0.3            py38haa244fe_1    conda-forge
cloudpickle               2.0.0              pyhd8ed1ab_0    conda-forge
colorama                  0.4.4              pyh9f0ad1d_0    conda-forge
cookiecutter              1.7.0                      py_0    conda-forge
cryptography              36.0.0           py38hb7941b4_0    conda-forge
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
dataclasses               0.8                pyhc8e2a94_3    conda-forge
debugpy                   1.5.1            py38h885f38d_0    conda-forge
decorator                 5.1.0              pyhd8ed1ab_0    conda-forge
defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
derivative                0.3.1                      py_0    conda-forge
diff-match-patch          20200713           pyh9f0ad1d_0    conda-forge
docutils                  0.17.1           py38haa244fe_1    conda-forge
entrypoints               0.3             pyhd8ed1ab_1003    conda-forge
flake8                    4.0.1              pyhd8ed1ab_0    conda-forge
fonttools                 4.28.3           py38h294d835_0    conda-forge
freetype                  2.10.4               h546665d_1    conda-forge
future                    0.18.2           py38haa244fe_4    conda-forge
icu                       68.2                 h0e60522_0    conda-forge
idna                      3.1                pyhd3deb0d_0    conda-forge
imagesize                 1.3.0              pyhd8ed1ab_0    conda-forge
importlib-metadata        4.8.2            py38haa244fe_0    conda-forge
importlib_metadata        4.8.2                hd8ed1ab_0    conda-forge
importlib_resources       5.4.0              pyhd8ed1ab_0    conda-forge
inflection                0.5.1              pyh9f0ad1d_0    conda-forge
intel-openmp              2021.4.0          h57928b3_3556    conda-forge
intervaltree              3.0.2                      py_0    conda-forge
ipykernel                 6.5.1            py38h595d716_0    conda-forge
ipython                   7.30.1           py38haa244fe_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
isort                     5.10.1             pyhd8ed1ab_0    conda-forge
jbig                      2.1               h8d14728_2003    conda-forge
jedi                      0.18.1           py38haa244fe_0    conda-forge
jellyfish                 0.8.9            py38h294d835_1    conda-forge
jinja2                    3.0.3              pyhd8ed1ab_0    conda-forge
jinja2-time               0.2.0                      py_2    conda-forge
joblib                    1.1.0              pyhd8ed1ab_0    conda-forge
jpeg                      9d                   h8ffe710_0    conda-forge
jsonschema                4.2.1              pyhd8ed1ab_1    conda-forge
jupyter_client            7.1.0              pyhd8ed1ab_0    conda-forge
jupyter_core              4.9.1            py38haa244fe_1    conda-forge
jupyterlab_pygments       0.1.2              pyh9f0ad1d_0    conda-forge
keyring                   23.4.0           py38haa244fe_0    conda-forge
kiwisolver                1.3.2            py38hbd9d945_1    conda-forge
lazy-object-proxy         1.6.0            py38h294d835_1    conda-forge
lcms2                     2.12                 h2a16943_0    conda-forge
lerc                      3.0                  h0e60522_0    conda-forge
libblas                   3.9.0                     8_mkl    conda-forge
libbrotlicommon           1.0.9                h8ffe710_6    conda-forge
libbrotlidec              1.0.9                h8ffe710_6    conda-forge
libbrotlienc              1.0.9                h8ffe710_6    conda-forge
libcblas                  3.9.0                     8_mkl    conda-forge
libclang                  11.1.0          default_h5c34c98_1    conda-forge
libdeflate                1.8                  h8ffe710_0    conda-forge
libiconv                  1.16                 he774522_0    conda-forge
liblapack                 3.9.0                     8_mkl    conda-forge
libpng                    1.6.37               h1d00b33_2    conda-forge
libsodium                 1.0.18               h8d14728_1    conda-forge
libspatialindex           1.9.3                h39d44d4_4    conda-forge
libtiff                   4.3.0                hd413186_2    conda-forge
libxml2                   2.9.12               hf5bbc77_1    conda-forge
libxslt                   1.1.33               h65864e5_3    conda-forge
libzlib                   1.2.11            h8ffe710_1013    conda-forge
llvmlite                  0.36.0           py38h57a6900_0    conda-forge
lxml                      4.6.4            py38h292cb97_0    conda-forge
lz4                       3.1.10           py38h34afd45_0    conda-forge
lz4-c                     1.9.3                h8ffe710_1    conda-forge
m2w64-gcc-libgfortran     5.3.0                         6    conda-forge
m2w64-gcc-libs            5.3.0                         7    conda-forge
m2w64-gcc-libs-core       5.3.0                         7    conda-forge
m2w64-gmp                 6.1.0                         2    conda-forge
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    conda-forge
markupsafe                2.0.1            py38h294d835_1    conda-forge
matplotlib                3.5.0            py38haa244fe_0    conda-forge
matplotlib-base           3.5.0            py38h1f000d6_0    conda-forge
matplotlib-inline         0.1.3              pyhd8ed1ab_0    conda-forge
mccabe                    0.6.1                      py_1    conda-forge
mistune                   0.8.4           py38h294d835_1005    conda-forge
mkl                       2020.4             hb70f87d_311    conda-forge
mpmath                    1.2.1              pyhd8ed1ab_0    conda-forge
msys2-conda-epoch         20160418                      1    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
mypy_extensions           0.4.3            py38haa244fe_4    conda-forge
natsort                   8.0.0              pyhd8ed1ab_0    conda-forge
nbclient                  0.5.9              pyhd8ed1ab_0    conda-forge
nbconvert                 6.3.0            py38haa244fe_1    conda-forge
nbformat                  5.1.3              pyhd8ed1ab_0    conda-forge
nest-asyncio              1.5.4              pyhd8ed1ab_0    conda-forge
numba                     0.53.1           py38h99fac5f_1    conda-forge
numexpr                   2.7.3            py38h5d928e2_2    conda-forge
numpy                     1.21.4           py38h089cfbf_0    conda-forge
numpydoc                  1.1.0                      py_1    conda-forge
olefile                   0.46               pyh9f0ad1d_1    conda-forge
openjpeg                  2.4.0                hb211442_1    conda-forge
openssl                   1.1.1l               h8ffe710_0    conda-forge
packaging                 21.3               pyhd8ed1ab_0    conda-forge
pandas                    1.3.4            py38h5d928e2_1    conda-forge
pandoc                    2.16.2               h8ffe710_0    conda-forge
pandocfilters             1.5.0              pyhd8ed1ab_0    conda-forge
paramiko                  2.8.1              pyhd8ed1ab_0    conda-forge
parso                     0.8.3              pyhd8ed1ab_0    conda-forge
pathspec                  0.9.0              pyhd8ed1ab_0    conda-forge
patsy                     0.5.2              pyhd8ed1ab_0    conda-forge
pexpect                   4.8.0              pyh9f0ad1d_2    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    8.4.0            py38h794f750_0    conda-forge
pip                       21.3.1             pyhd8ed1ab_0    conda-forge
platformdirs              2.3.0              pyhd8ed1ab_0    conda-forge
pluggy                    1.0.0            py38haa244fe_2    conda-forge
poyo                      0.5.0                      py_0    conda-forge
prompt-toolkit            3.0.24             pyha770c72_0    conda-forge
psutil                    5.8.0            py38h294d835_2    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
pycodestyle               2.8.0              pyhd8ed1ab_0    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pydocstyle                6.1.1              pyhd8ed1ab_0    conda-forge
pyflakes                  2.4.0              pyhd8ed1ab_0    conda-forge
pygments                  2.10.0             pyhd8ed1ab_0    conda-forge
pylint                    2.12.2             pyhd8ed1ab_0    conda-forge
pyls-spyder               0.4.0              pyhd8ed1ab_0    conda-forge
pynacl                    1.4.0            py38h31c79cd_3    conda-forge
pyopenssl                 21.0.0             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.6              pyhd8ed1ab_0    conda-forge
pyqt                      5.12.3           py38haa244fe_8    conda-forge
pyqt-impl                 5.12.3           py38h885f38d_8    conda-forge
pyqt5-sip                 4.19.18          py38h885f38d_8    conda-forge
pyqtchart                 5.12             py38h885f38d_8    conda-forge
pyqtwebengine             5.12.1           py38h885f38d_8    conda-forge
pyrsistent                0.18.0           py38h294d835_0    conda-forge
pysindy                   1.3.0              pyhd3deb0d_0    conda-forge
pysocks                   1.7.1            py38haa244fe_4    conda-forge
python                    3.8.12          h7840368_2_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-lsp-black          1.0.1              pyhd8ed1ab_0    conda-forge
python-lsp-jsonrpc        1.0.0              pyhd8ed1ab_0    conda-forge
python-lsp-server         1.3.2              pyhd8ed1ab_0    conda-forge
python_abi                3.8                      2_cp38    conda-forge
pytz                      2021.3             pyhd8ed1ab_0    conda-forge
pywin32                   302              py38h294d835_2    conda-forge
pywin32-ctypes            0.2.0           py38haa244fe_1004    conda-forge
pyyaml                    6.0              py38h294d835_3    conda-forge
pyzmq                     22.3.0           py38h09162b1_1    conda-forge
qdarkstyle                3.0.2              pyhd8ed1ab_0    conda-forge
qstylizer                 0.2.1              pyhd8ed1ab_0    conda-forge
qt                        5.12.9               h5909a2a_4    conda-forge
qtawesome                 1.1.1              pyhd8ed1ab_0    conda-forge
qtconsole                 5.2.1              pyhd8ed1ab_0    conda-forge
qtpy                      1.11.3             pyhd8ed1ab_0    conda-forge
regex                     2021.11.10       py38h294d835_0    conda-forge
requests                  2.26.0             pyhd8ed1ab_1    conda-forge
rope                      0.22.0             pyhd8ed1ab_0    conda-forge
rtree                     0.9.7            py38h8b54edf_3    conda-forge
scikit-learn              1.0.1            py38hb60ee80_2    conda-forge
scipy                     1.7.3            py38ha1292f7_0    conda-forge
seaborn                   0.11.2               hd8ed1ab_0    conda-forge
seaborn-base              0.11.2             pyhd8ed1ab_0    conda-forge
setuptools                59.4.0           py38haa244fe_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
snowballstemmer           2.2.0              pyhd8ed1ab_0    conda-forge
sortedcontainers          2.4.0              pyhd8ed1ab_0    conda-forge
sphinx                    4.3.1              pyh6c4a22f_0    conda-forge
sphinxcontrib-applehelp   1.0.2                      py_0    conda-forge
sphinxcontrib-devhelp     1.0.2                      py_0    conda-forge
sphinxcontrib-htmlhelp    2.0.0              pyhd8ed1ab_0    conda-forge
sphinxcontrib-jsmath      1.0.1                      py_0    conda-forge
sphinxcontrib-qthelp      1.0.3                      py_0    conda-forge
sphinxcontrib-serializinghtml 1.1.5              pyhd8ed1ab_1    conda-forge
spyder                    5.2.0            py38haa244fe_0    conda-forge
spyder-kernels            2.2.0            py38haa244fe_0    conda-forge
sqlite                    3.37.0               h8ffe710_0    conda-forge
statsmodels               0.13.1           py38h6f4d8f0_0    conda-forge
sympy                     1.9              py38haa244fe_1    conda-forge
testpath                  0.5.0              pyhd8ed1ab_0    conda-forge
textdistance              4.2.2              pyhd8ed1ab_0    conda-forge
threadpoolctl             3.0.0              pyh8a188c0_0    conda-forge
three-merge               0.1.1              pyh9f0ad1d_0    conda-forge
tinycss2                  1.1.1              pyhd8ed1ab_0    conda-forge
tk                        8.6.11               h8ffe710_1    conda-forge
toml                      0.10.2             pyhd8ed1ab_0    conda-forge
tomli                     1.2.2              pyhd8ed1ab_0    conda-forge
tornado                   6.1              py38h294d835_2    conda-forge
traitlets                 5.1.1              pyhd8ed1ab_0    conda-forge
typed-ast                 1.5.1            py38h294d835_0    conda-forge
typing-extensions         4.0.1                hd8ed1ab_0    conda-forge
typing_extensions         4.0.1              pyha770c72_0    conda-forge
ucrt                      10.0.20348.0         h57928b3_0    conda-forge
ujson                     4.2.0            py38h885f38d_1    conda-forge
unicodedata2              13.0.0.post2     py38h294d835_4    conda-forge
urllib3                   1.26.7             pyhd8ed1ab_0    conda-forge
vc                        14.2                 hb210afc_5    conda-forge
vs2015_runtime            14.29.30037          h902a5da_5    conda-forge
watchdog                  2.1.6            py38haa244fe_1    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
webencodings              0.5.1                      py_1    conda-forge
wheel                     0.37.0             pyhd8ed1ab_1    conda-forge
whichcraft                0.6.1                      py_0    conda-forge
win_inet_pton             1.1.0            py38haa244fe_3    conda-forge
wrapt                     1.13.3           py38h294d835_1    conda-forge
xlrd                      2.0.1              pyhd8ed1ab_3    conda-forge
xlsxwriter                3.0.2              pyhd8ed1ab_0    conda-forge
xlwt                      1.3.0                      py_1    conda-forge
xz                        5.2.5                h62dcd97_1    conda-forge
yaml                      0.2.5                he774522_0    conda-forge
yapf                      0.31.0             pyhd8ed1ab_0    conda-forge
zeromq                    4.3.4                h0e60522_1    conda-forge
zipp                      3.6.0              pyhd8ed1ab_0    conda-forge
zlib                      1.2.11            h8ffe710_1013    conda-forge
zstd                      1.5.0                h6255e5f_0    conda-forge
```
</details>

**Comment by akaptano** [comment]
See Issue #124 ... the solution is either to use PySINDy version < 1.5 with scikit-learn version < 1.0, or use PySINDy version >= 1.5 and any scikit-learn version. Your issue is that you are using an older version of PySINDy, with a newer version of scikit-learn. Closing this for now but feel free to comment if you continue to have issues.

**Comment by zariiii9003** [comment]
I just assumed that i had the latest version since i created a fresh conda environment. The version on conda-forge is pretty old then.

Thank you for your quick help. I will try the latest version tomorrow.
