### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by engsbk** [dynamicslab/pysindy#146]
### Reproducing code example:
After cloning the repo from the fork I made. I executed this line from my directory:

`pip install .`
### Error message:
```
Traceback (most recent call last):
  File "/Users/shaikhahalkhadhr/anaconda3/bin/pip", line 7, in <module>
    from pip._internal.cli.main import main
  File "/Users/shaikhahalkhadhr/anaconda3/lib/python3.7/site-packages/pip/_internal/cli/main.py", line 8, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/Users/shaikhahalkhadhr/anaconda3/lib/python3.7/site-packages/pip/_internal/cli/autocompletion.py", line 9, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/Users/shaikhahalkhadhr/anaconda3/lib/python3.7/site-packages/pip/_internal/cli/main_parser.py", line 7, in <module>
    from pip._internal.cli import cmdoptions
  File "/Users/shaikhahalkhadhr/anaconda3/lib/python3.7/site-packages/pip/_internal/cli/cmdoptions.py", line 22, in <module>
    from pip._internal.cli.progress_bars import BAR_TYPES
  File "/Users/shaikhahalkhadhr/anaconda3/lib/python3.7/site-packages/pip/_internal/cli/progress_bars.py", line 9, in <module>
    from pip._internal.utils.logging import get_indentation
  File "/Users/shaikhahalkhadhr/anaconda3/lib/python3.7/site-packages/pip/_internal/utils/logging.py", line 14, in <module>
    from pip._internal.utils.misc import ensure_dir
  File "/Users/shaikhahalkhadhr/anaconda3/lib/python3.7/site-packages/pip/_internal/utils/misc.py", line 29, in <module>
    from pip._internal.locations import get_major_minor_version, site_packages, user_site
  File "/Users/shaikhahalkhadhr/anaconda3/lib/python3.7/site-packages/pip/_internal/locations/__init__.py", line 14, in <module>
    from . import _distutils, _sysconfig
  File "/Users/shaikhahalkhadhr/anaconda3/lib/python3.7/site-packages/pip/_internal/locations/_sysconfig.py", line 8, in <module>
    from pip._internal.exceptions import InvalidSchemeCombination, UserInstallationInvalid
ImportError: cannot import name 'InvalidSchemeCombination' from 'pip._internal.exceptions' (/Users/shaikhahalkhadhr/anaconda3/lib/python3.7/site-packages/pip/_internal/exceptions.py)
```
### PySINDy/Python version information:
I did not get to install pysindy from source code so I don't have the version.
Python version: 3.7.7

**Comment by akaptano** [comment]
As far as I can tell, none of these files has anything to do with PySINDy. Can you install other packages with pip this way?

**Comment by engsbk** [comment]
Never mind, it was a pip problem on MAC OS.

This can be resolved with these two lines:
```
curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
python get-pip.py
```
