### ISSUE TITLE
[BUG] Error in fit() method

### ISSUE THREAD

**Issue by lahoff** [dynamicslab/pysindy#190]
Hi! I've installed pysindy in my Windows and Mac (via pip)
In all of them when I try to simply run the toy examples I get the same error 
I tried with python 3.8, 3.9 and 3.10

Thanks!

### Reproducing code example:

x = np.load('./DATA/data.npy')
t = np.arange(0, 10, 0.01)

model = ps.SINDy()
model.fit(x, t=t)

### Error message:

Traceback (most recent call last):
  File "...\PycharmProjects\DataScience\DynamicalSystems\PYSINDy.py", line 16, in <module>
    model.fit(x, t=t)
  File "...\PycharmProjects\DataScience\.venv\lib\site-packages\pysindy\pysindy.py", line 563, in fit
    self.model.fit(x, x_dot)
  File "...\PycharmProjects\DataScience\.venv\lib\site-packages\sklearn\pipeline.py", line 382, in fit
    self._final_estimator.fit(Xt, y, **fit_params_last_step)
  File "...\PycharmProjects\DataScience\.venv\lib\site-packages\pysindy\optimizers\sindy_optimizer.py", line 58, in fit
    self.optimizer.fit(x, y)
  File "...s\PycharmProjects\DataScience\.venv\lib\site-packages\pysindy\optimizers\base.py", line 134, in fit
    x, y, X_offset, y_offset, X_scale = self._preprocess_data(
AttributeError: 'STLSQ' object has no attribute '_preprocess_data'

**Comment by Jacob-Stevens-Haas** [comment]
Sounds like same issue as in #179.  Tl; dr: scikit-learn changed where we import `_preprocess_data()` from.  What are your pysindy and sklearn versions?
