### ISSUE TITLE
[BUG] - Example 2_introduction_to_sindy.ipynb not running with scikit-learn > 1.0

### ISSUE THREAD

**Issue by edumagol** [dynamicslab/pysindy#196]
The jupyter notebook provided at https://github.com/dynamicslab/pysindy/blob/master/examples/2_introduction_to_sindy.ipynb is not running with scikit-learn > 1.0 

I downgraded scikit-learn to version 0.24 and it run fine. But when I had scikit-learn version 1.1 it did not run, as I show bellow.

### Reproducing code example:

import pysindy
import numpy as np
import pysindy as ps
import sys
import pysindy
print(pysindy.__version__, sys.version)

t = np.linspace(0, 1, 100)
x = 3 * np.exp(-2 * t)
y = 0.5 * np.exp(t)
X = np.stack((x, y), axis=-1)  # First column is x, second is y

differentiation_method = ps.FiniteDifference(order=2)
feature_library = ps.PolynomialLibrary(degree=3)
optimizer = ps.STLSQ(threshold=0.2)

model = ps.SINDy(
    differentiation_method=differentiation_method,
    feature_library=feature_library,
    optimizer=optimizer,
    feature_names=["x", "y"]
)

model.fit(X, t=t)

model.print()

### Error message:

Traceback (most recent call last):
  File "C:\Users\eduardo.magalhaes\pythonprojects\research\pysindy\main.py", line 23, in <module> 
    model.fit(X, t=t)
  File "C:\Users\eduardo.magalhaes\Envs\kalman\lib\site-packages\pysindy\pysindy.py", line 563, in fit
    self.model.fit(x, x_dot)
  File "C:\Users\eduardo.magalhaes\Envs\kalman\lib\site-packages\sklearn\pipeline.py", line 382, in fit
    self._final_estimator.fit(Xt, y, **fit_params_last_step)
  File "C:\Users\eduardo.magalhaes\Envs\kalman\lib\site-packages\pysindy\optimizers\sindy_optimizer.py", line 58, in fit
    self.optimizer.fit(x, y)
  File "C:\Users\eduardo.magalhaes\Envs\kalman\lib\site-packages\pysindy\optimizers\base.py", line 134, in fit
    x, y, X_offset, y_offset, X_scale = self._preprocess_data(
AttributeError: 'STLSQ' object has no attribute '_preprocess_data'

### PySINDy/Python version information:

1.7 3.9.6 (tags/v3.9.6:db3ff76, Jun 28 2021, 15:26:21) [MSC v.1929 64 bit (AMD64)]

**Comment by akaptano** [comment]
See Issue #179. We are working on a simple fix.

**Comment by edumagol** [comment]
Sure, thanks!
