### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by draconcio12** [dynamicslab/pysindy#208]
AttributeError: 'STLSQ' object has no attribute '_preprocess_data', Running the example

### Reproducing code example:
model = ps.SINDy(feature_names=["x", "y"])
model.fit(X, t=t)

### Error message:

AttributeError: 'STLSQ' object has no attribute '_preprocess_data'

### PySINDy/Python version information:

1.7 3.8.10 (default, Mar 15 2022, 12:22:08) 
[GCC 9.4.0]

**Comment by akaptano** [comment]
See Issue #179. You need an older version of sklearn (1.0 or older) or the newest version of the main branch.

**Comment by panandreou** [comment]
I don't understand how to fix the problem. pip does not allow me to put an older version of sklearn and I don't
understand what is meant of the newest version of the main branch. I have the latest python and the latest pysindy.

**Comment by Jacob-Stevens-Haas** [comment]
> pip does not allow me to put an older version of sklearn

What is the output of 
```
pip install scikit-learn~=0.0
```

**Comment by panandreou** [comment]
Collecting scikit-learn~=0.0
  Downloading scikit-learn-0.24.2.tar.gz (7.5 MB)
     ---------------------------------------- 7.5/7.5 MB 7.2 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [57 lines of output]

**Comment by panandreou** [comment]
C:\Users\pant1>pip install scikit-learn~=0.0
Collecting scikit-learn~=0.0
  Using cached scikit-learn-0.24.2.tar.gz (7.5 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [57 lines of output]
      Partial import of sklearn during the build process.
      setup.py:116: DeprecationWarning:

        `numpy.distutils` is deprecated since NumPy 1.23.0, as a result
        of the deprecation of `distutils` itself. It will be removed for
        Python >= 3.12. For older Python versions it will remain present.
        It is recommended to use `setuptools < 60.0` for those Python versions.
        For more details, see:
          https://numpy.org/devdocs/reference/distutils_status_migration.html


        from numpy.distutils.command.build_ext import build_ext  # noqa
      INFO: No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      Traceback (most recent call last):
        File "C:\Users\pant1\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 363, in <module>
          main()
        File "C:\Users\pant1\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\pant1\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 164, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "C:\Users\pant1\AppData\Local\Temp\pip-build-env-sf6b3_un\overlay\Lib\site-packages\setuptools\build_meta.py", line 188, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "C:\Users\pant1\AppData\Local\Temp\pip-build-env-sf6b3_un\overlay\Lib\site-packages\setuptools\build_meta.py", line 281, in run_setup
          super(_BuildMetaLegacyBackend,
        File "C:\Users\pant1\AppData\Local\Temp\pip-build-env-sf6b3_un\overlay\Lib\site-packages\setuptools\build_meta.py", line 174, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 301, in <module>
          setup_package()
        File "setup.py", line 297, in setup_package
          setup(**metadata)
        File "C:\Users\pant1\AppData\Local\Temp\pip-build-env-sf6b3_un\overlay\Lib\site-packages\numpy\distutils\core.py", line 135, in setup
          config = configuration()
        File "setup.py", line 188, in configuration
          config.add_subpackage('sklearn')
        File "C:\Users\pant1\AppData\Local\Temp\pip-build-env-sf6b3_un\overlay\Lib\site-packages\numpy\distutils\misc_util.py", line 1050, in add_subpackage
          config_list = self.get_subpackage(subpackage_name, subpackage_path,
        File "C:\Users\pant1\AppData\Local\Temp\pip-build-env-sf6b3_un\overlay\Lib\site-packages\numpy\distutils\misc_util.py", line 1016, in get_subpackage
          config = self._get_configuration_from_setup_py(
        File "C:\Users\pant1\AppData\Local\Temp\pip-build-env-sf6b3_un\overlay\Lib\site-packages\numpy\distutils\misc_util.py", line 958, in _get_configuration_from_setup_py
          config = setup_module.configuration(*args)
        File "C:\Users\pant1\AppData\Local\Temp\pip-install-wgyw360r\scikit-learn_1310c08d0e78416b86f9dbad1af0c35c\sklearn\setup.py", line 83, in configuration
          cythonize_extensions(top_path, config)
        File "C:\Users\pant1\AppData\Local\Temp\pip-install-wgyw360r\scikit-learn_1310c08d0e78416b86f9dbad1af0c35c\sklearn\_build_utils\__init__.py", line 45, in cythonize_extensions
          basic_check_build()
        File "C:\Users\pant1\AppData\Local\Temp\pip-install-wgyw360r\scikit-learn_1310c08d0e78416b86f9dbad1af0c35c\sklearn\_build_utils\pre_build_helpers.py", line 106, in basic_check_build
          compile_test_program(code)
        File "C:\Users\pant1\AppData\Local\Temp\pip-install-wgyw360r\scikit-learn_1310c08d0e78416b86f9dbad1af0c35c\sklearn\_build_utils\pre_build_helpers.py", line 66, in compile_test_program
          ccompiler.compile(['test_program.c'], output_dir='objects',
        File "C:\Users\pant1\AppData\Local\Temp\pip-build-env-sf6b3_un\overlay\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 361, in compile
          self.initialize()
        File "C:\Users\pant1\AppData\Local\Temp\pip-build-env-sf6b3_un\overlay\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 241, in initialize
          vc_env = _get_vc_env(plat_spec)
        File "C:\Users\pant1\AppData\Local\Temp\pip-build-env-sf6b3_un\overlay\Lib\site-packages\setuptools\msvc.py", line 316, in msvc14_get_vc_env
          return _msvc14_get_vc_env(plat_spec)
        File "C:\Users\pant1\AppData\Local\Temp\pip-build-env-sf6b3_un\overlay\Lib\site-packages\setuptools\msvc.py", line 270, in _msvc14_get_vc_env
          raise distutils.errors.DistutilsPlatformError(
      distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

C:\Users\pant1>

**Comment by Jacob-Stevens-Haas** [comment]
Ok wow.  Looks like this is an issue installing numpy in the push to make packages PEP-517 compliant.  What is your pip version?  AFAIK, pip version 22 is the first one with full PEP-517 compatibility.  Try upgrading pip if it isn't already at version 22.

This is the limit of my knowledge.  If upgrading pip doesn't work, you will have to look for answers of how to install sklearn/numpy.

**Comment by Jacob-Stevens-Haas** [comment]
Alternatively, clone the repo and install the current version of `master`, as Alan said above.  The next release will be compatible with scikit-learn~=1.0

```
git clone https://github.com/dynamicslab/pysindy
pip install ./pysindy
```

**Comment by panandreou** [comment]
Hello Jacob,
thank you. It worked.
Regards,
Pantelis
