### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Lauanbpm** [dynamicslab/pysindy#217]
The program has an error when the model.fit function is called

### Reproducing code example:

```python
import numpy as np
from scipy.integrate import odeint
from pysindy import SINDy
from pysindy.optimizers import STLSQ
lorenz = lambda z,t : [10*(z[1] - z[0]),
                        z[0]*(28 - z[2]) - z[1],
                        z[0]*z[1] - 8/3*z[2]]
t = np.arange(0,2,.002)
x = odeint(lorenz, [-8,8,27], t)
opt = STLSQ(threshold=.1, alpha=.5)
model = SINDy(optimizer=opt)
model.fit(x, t=t[1]-t[0])
model.print()
```

### Error message:

Traceback (most recent call last):

  File "C:\Users\l4u4n\anaconda3\envs\py39env\lib\site-packages\spyder_kernels\py3compat.py", line 356, in compat_exec
    exec(code, globals, locals)

  File "c:\users\l4u4n\google drive (lhaua.barbosa@gmail.com)\lamec - drive\programas\machine learning\trabalhos\pysindy\pysindy_exemple_2.py", line 20, in <module>
    model.fit(x, t=t[1]-t[0])

  File "C:\Users\l4u4n\anaconda3\envs\py39env\lib\site-packages\pysindy\pysindy.py", line 563, in fit
    self.model.fit(x, x_dot)

  File "C:\Users\l4u4n\anaconda3\envs\py39env\lib\site-packages\sklearn\pipeline.py", line 382, in fit
    self._final_estimator.fit(Xt, y, **fit_params_last_step)

  File "C:\Users\l4u4n\anaconda3\envs\py39env\lib\site-packages\pysindy\optimizers\sindy_optimizer.py", line 58, in fit
    self.optimizer.fit(x, y)

  File "C:\Users\l4u4n\anaconda3\envs\py39env\lib\site-packages\pysindy\optimizers\base.py", line 134, in fit
    x, y, X_offset, y_offset, X_scale = self._preprocess_data(

AttributeError: 'STLSQ' object has no attribute '_preprocess_data'

### PySINDy/Python version information:

1.7 3.9.12 | packaged by conda-forge | (main, Mar 24 2022, 23:17:03) [MSC v.1929 64 bit (AMD64)]

**Comment by Jacob-Stevens-Haas** [comment]
Downgrade sklearn < 1.0, see issue #179
