### ISSUE TITLE
Cannot simulate from SINDy-PI model

### ISSUE THREAD

**Issue by tomshafer** [dynamicslab/pysindy#287]
After fitting a model using the `pysindy.SINDyPI` optimizer, I cannot `.simulate()` from the model with non-training data (not can I `.predict()`). Am I missing a trick?

### Reproducing code example 1 w/traceback (`.predict()`):

```python
import pysindy as ps
import numpy as np
from scipy.integrate import solve_ivp

# Get training data for pendulum + cart
soln = solve_ivp(ps.utils.odes.pendulum_on_cart, (0, 16), [0.3, 0, 1, 0], dense_output=True)

ttrain = np.arange(0, 12.01, 0.01)
xtrain = soln.sol(ttrain)[0]

ttest = np.arange(12, 16.01, 0.01)
xtest = soln.sol(ttest)[0]

# Solve 2nd-order ODE with implicit terms 
fns = [ ... ]
nms = [ ... ]

library = ps.PDELibrary(
    library_functions=fns,
    function_names=nms,
    derivative_order=2,
    temporal_grid=ttrain,
    include_bias=True,
    implicit_terms=True,
)

optim = ps.SINDyPI()
model = ps.SINDy(optim, library)
model.fit(xtrain, ttrain)

# Retrodict training data -- OK
model.predict(xtrain)

# Predict test data -- IndexError
model.predict(xtest)
```

<details>
<summary>Traceback</summary>

```
IndexError                                Traceback (most recent call last)
Cell In[6], line 1
----> 1 model.predict(xtest)

File venv/lib/python3.10/site-packages/pysindy/pysindy.py:477, in SINDy.predict(self, x, u, multiple_trajectories)
    475     u = validate_control_variables(x, u)
    476     x = [np.concatenate((xi, ui), axis=xi.ax_coord) for xi, ui in zip(x, u)]
--> 477 result = [self.model.predict([xi]) for xi in x]
    478 result = [
    479     self.feature_library.reshape_samples_to_spatial_grid(pred)
    480     for pred in result
    481 ]
    483 # Kept for backwards compatibility.

File venv/lib/python3.10/site-packages/pysindy/pysindy.py:477, in <listcomp>(.0)
    475     u = validate_control_variables(x, u)
    476     x = [np.concatenate((xi, ui), axis=xi.ax_coord) for xi, ui in zip(x, u)]
--> 477 result = [self.model.predict([xi]) for xi in x]
    478 result = [
    479     self.feature_library.reshape_samples_to_spatial_grid(pred)
    480     for pred in result
    481 ]
    483 # Kept for backwards compatibility.

File venv/lib/python3.10/site-packages/sklearn/utils/metaestimators.py:113, in _AvailableIfDescriptor.__get__.<locals>.<lambda>(*args, **kwargs)
    110         raise attr_err
    112     # lambda, but not partial, allows help() to work with update_wrapper
--> 113     out = lambda *args, **kwargs: self.fn(obj, *args, **kwargs)  # noqa
    114 else:
    116     def fn(*args, **kwargs):

File venv/lib/python3.10/site-packages/sklearn/pipeline.py:469, in Pipeline.predict(self, X, **predict_params)
    467 Xt = X
    468 for _, name, transform in self._iter(with_final=False):
--> 469     Xt = transform.transform(Xt)
    470 return self.steps[-1][1].predict(Xt, **predict_params)

File venv/lib/python3.10/site-packages/pysindy/feature_library/base.py:191, in x_sequence_or_item.<locals>.func(self, x, *args, **kwargs)
    189 if isinstance(x, Sequence):
    190     xs = [AxesArray(xi, comprehend_axes(xi)) for xi in x]
--> 191     result = wrapped_func(self, xs, *args, **kwargs)
    192     if isinstance(result, Sequence):  # e.g. transform() returns x
    193         return [AxesArray(xp, comprehend_axes(xp)) for xp in result]

File venv/lib/python3.10/site-packages/pysindy/feature_library/pde_library.py:429, in PDELibrary.transform(self, x_full)
    422         s[axis] = slice(self.spatiotemporal_grid.shape[axis])
    423         s[-1] = axis
    425         derivs = self.differentiation_method(
    426             d=multiindex[axis],
    427             axis=axis,
    428             **self.diff_kwargs,
--> 429         )._differentiate(derivs, self.spatiotemporal_grid[tuple(s)])
    430 library_derivatives[
    431     ..., library_idx : library_idx + n_features
    432 ] = derivs
    433 library_idx += n_features

File venv/lib/python3.10/site-packages/pysindy/differentiation/finite_difference.py:252, in FiniteDifference._differentiate(self, x, t)
    250 else:
    251     coeffs = self._coefficients(t)
--> 252     interior = self._accumulate(coeffs, x)
    253 s[self.axis] = slice((self.n_stencil - 1) // 2, -(self.n_stencil - 1) // 2)
    254 x_dot[tuple(s)] = interior

File venv/lib/python3.10/site-packages/pysindy/differentiation/finite_difference.py:214, in FiniteDifference._accumulate(self, coeffs, x)
    207 # a new axis is introduced after self.axis for the stencil indices
    208 # To contract with the coefficients, roll by -self.axis to put it first
    209 # Then roll back by self.axis to return the order
    210 trans = np.roll(np.arange(len(x.shape) + 1), -self.axis)
    211 return np.transpose(
    212     np.einsum(
    213         "ij...,ij->j...",
--> 214         np.transpose(x[tuple(s)], axes=trans),
    215         np.transpose(coeffs),
    216     ),
    217     np.roll(np.arange(len(x.shape)), self.axis),
    218 )

IndexError: index 402 is out of bounds for axis 0 with size 402
```

</details>

### Reproducing code example 2 w/traceback (`.simulate()`):

Same setup as above, and then this one crashes Python.

```python
# Simulate test data -- not OK!
model.simulate(xtest, ttest)
```

<details>
<summary>Traceback</summary>

```
Traceback (most recent call last):
  File "venv/lib/python3.10/site-packages/scipy/integrate/_ivp/base.py", line 138, in fun
capi_return is NULL
Call-back cb_f_in_lsoda__user__routines failed.
Fatal Python error: F2PySwapThreadLocalCallbackPtr: F2PySwapThreadLocalCallbackPtr: PyLong_AsVoidPtr failed
Python runtime state: initialized
    return self.fun_single(t, y)
  File "venv/lib/python3.10/site-packages/scipy/integrate/_ivp/base.py", line 20, in fun_wrapped
    return np.asarray(fun(t, y), dtype=dtype)
  File "venv/lib/python3.10/site-packages/pysindy/pysindy.py", line 860, in rhs
    return self.predict(x[np.newaxis, :])[0]
  File "venv/lib/python3.10/site-packages/pysindy/pysindy.py", line 477, in predict
    result = [self.model.predict([xi]) for xi in x]
  File "venv/lib/python3.10/site-packages/pysindy/pysindy.py", line 477, in <listcomp>
    result = [self.model.predict([xi]) for xi in x]
  File "venv/lib/python3.10/site-packages/sklearn/utils/metaestimators.py", line 113, in <lambda>
    out = lambda *args, **kwargs: self.fn(obj, *args, **kwargs)  # noqa
  File "venv/lib/python3.10/site-packages/sklearn/pipeline.py", line 469, in predict
    Xt = transform.transform(Xt)
  File "venv/lib/python3.10/site-packages/pysindy/feature_library/base.py", line 191, in func
    result = wrapped_func(self, xs, *args, **kwargs)
  File "venv/lib/python3.10/site-packages/pysindy/feature_library/pde_library.py", line 404, in transform
    raise ValueError("x shape does not match training shape")
ValueError: x shape does not match training shape
```

</details>

### PySINDy/Python version information:

```
1.7.3 3.10.9 | packaged by conda-forge | (main, Feb  2 2023, 20:24:27) [Clang 14.0.6 ]
```

**Comment by akaptano** [comment]
Two problems with using model.simulate here:
(1) model.simulate only works for a set of 1st order ODEs, so you have to reduce your second order equations to a set of 1st order ODEs.
(2) If you have implicit terms, i.e. your ordinary differential equations look like dx/dt = f(x, dx/dt) (once they are reduced to the set of first order equations), this is a differential algebraic equation (DAE). DAEs cannot be integrated with model.simulate, which is just a wrapper function for scipy.solve_ivp or scipy.odeint. In general, you need to use a DAE solver like that from diffeqpy or other external package. This is a lot of work, so folks often just look at the error in the coefficients and the errors in model.predict for the pendulum on the cart or similar implicit problem of this type.

**Comment by tomshafer** [comment]
Thanks, very helpful. Cheers!
